# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Build and Test Server Projects"

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "ap-southeast-2"

permissions:
  contents: read # for actions/checkout
  id-token: write # for aws-actions/configure-aws-credentials

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials for China region audience
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ${{ env.AWS_REGION}}
        role-to-assume: arn:aws:iam::572169125256:role/github-action

    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./server/GraphQLDemo
      run: dotnet restore GraphQLDemo.sln
    - name: Build
      working-directory: ./server/GraphQLDemo
      run: dotnet build GraphQLDemo.sln --no-restore
    - name: Test
      working-directory: ./server/GraphQLDemo
      run: dotnet test GraphQLDemo.sln --no-build --verbosity normal
